wellRead/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'users#index'

resources :my_books do
    resources :reviews
    resources :quotes
    resources :lends
end
resources :books do
    resources :conversations do
        resources :chats
    end
end
resources :users do
    resources :borrows
end
resources :libraries
resources :editions
resources :ratings
resources :sessions

get '/search', to: 'books#search'
get '/search', to: 'my_books#search'
post '/booksearch', to: 'books#searchtobook'
post '/my_booksearch', to: 'my_books#searchtomybook'
post '/edition', to: 'edition#create'
post '/chats/new', to: 'chats#create'
post '/borrows/new', to: 'borrows#create'
post 'chats/show', to: 'conversation#show'
# patch '/reviews/update', to: 'reviews#update'
# get '/reviews/edit' to: 'reviews#update'
# post '/reviews/:id/edit', to: 'reviews#update'


end

wellRead/app/models/book.rb
class Book < ApplicationRecord

  has_many :conversations
  has_many :my_books, through: :editions
  has_many :editions
  has_many :ratings
  # belongs to a category

  accepts_nested_attributes_for :conversations

end

wellRead/app/models/borrow.rb
class Borrow < ApplicationRecord
    belongs_to :user
end

wellRead/app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :conversation

end

wellRead/app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :user
  belongs_to :book
  has_many :chats

  accepts_nested_attributes_for :chats

end

wellRead/app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :book

  has_many :my_book

end

wellRead/app/models/lend.rb
class Lend < ApplicationRecord
  belongs_to :my_book
end

wellRead/app/models/library.rb
class Library < ApplicationRecord

  has_many :my_books

  belongs_to :user

end

wellRead/app/models/my_book.rb
class MyBook < ApplicationRecord

  # belongs_to :library
  belongs_to :edition
  has_one :lend
  has_many :reviews
  has_many :quotes
  has_many :books, through: :editions

  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :quotes
  accepts_nested_attributes_for :lend

  # def self.search(search)
  #   MyBook.fuzzy_search(search)
  #   end

end

wellRead/app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :my_book

    mount_uploader :image, QuoteUploader
end

wellRead/app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

wellRead/app/models/review.rb
class Review < ApplicationRecord


  belongs_to :my_book, foreign_key: :my_book_id
 
end

wellRead/app/models/user.rb
class User < ApplicationRecord


  has_secure_password

  has_one :library
  has_many :my_books, through: :library
  has_many :reviews, through: :my_books
  has_many :lends
  has_many :quotes
  has_many :conversations
  has_many :chats
  has_many :borrows
  has_many :ratings

  # accepts_nested_attributes_for :borrows

  # validates :password, length: { minimum: 6 }, on: :create
  # validates :password, confirmation: true, on: :create
  # validates :password_confirmation, presence: true, on: :create
  # validates_uniqueness_of :username, :message => ": This username is already registered!"
  # validates_presence_of :username
  # VALID_EMAIL_REGEX =  /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b
  # validates_presence_of :email, format: {with VALID_EMAIL_REGEX}
  # validates_uniqueness_of :email, :message => ": This email is already registered!"

end

wellRead/app/controllers/my_books_controller.rb
class MyBooksController < ApplicationController
    before_action :find_lend, only: [:show]

  def index
    @user = current_user
    @my_books = MyBook.where(user_id: @user.id)
    @reviews = Review.where(user_id: @user.id)
    @quotes = Quote.where(user_id: @user.id)
    # @my_search = MyBook.search(params[:search])
    #   if @my_search.size == 0
    #     @my_search = @my_books
    #   end
    #   respond_to do |format|
    #     format.html
    #     format.json { render json: @my_search }
    #   end
    # raise "hi meg"
  end

  def new
    @my_book = MyBook.new
  end

  def create
    @my_book = MyBook.new(my_book_params)

    if @my_book.save
      redirect_to library_url
    else
      render :new
    end


  end

  def show

    @user = current_user
    @my_book = MyBook.find(params[:id])
    @book = Book.find(@my_book.edition.book_id)
    #@my_books = Edition.where(user_id: @user.id)
    # @edition = Edition.find_by(edition_id: edition_id)
    @reviews = Review.where(user_id: @user.id)
    @quotes = Quote.where(user_id: @user.id)
    #edition = Edition.find(@my_book.edition_id)
    #@rating = Rating.find_by(user_id: @user.id, book_id: edition.book_id)
    @rating = Rating.find_by(user_id: @user.id, book_id: @my_book.edition.book_id)

  end

    def edit
    @my_book = MyBook.find(params[:id])
        if @my_book.update_attributes(my_book_params)
            # insert flash alert that changes have been saved
            redirect_to :back
        else
            redirect_to :back
        end
    end

    def new_edition
        @edition = Edition.new(edition_params)
        @edition.book_id = @book.id
        @edition.save!
    end

    def new_mybook
        @my_book = MyBook.new(my_book_params)
        @my_book.edition_id = @edition.id
        @my_book.user_id = @user.id
        @my_book.save!
    end

    def new_book
        @book = Book.new(book_params)
        @book.save!
    end

    def searchtomybook
    @user = current_user
    @my_book = MyBook.find_by edition_id: params["edition_id"]
        if @my_book == nil
            @edition = Edition.find_by title: params["title"],author: params["author"]
                if @edition == nil
                    @book = Book.find_by title: params["title"], author: params["author"]
                    if @book == nil #no my book, no edition, no book
                        new_book

                        new_edition

                        new_mybook

                    else #book exists, no edition, no mybook
                        new_edition

                        new_mybook

                    end #end of if book doesn't exist

                end # end of if edition doesn't exist
            new_mybook

        end #end of if my book doesn't exist
        unless MyBook.find_by(user_id:current_user.id, edition_id:@edition.id)

            @my_book.save!
            # @my_books = MyBook.where(user_id: current_user.id)
            redirect_to my_book_path(@my_book.id)
        else
            @user = current_user
            # @my_books = MyBook.where(user_id: @user.id)
            redirect_to my_book_path(@my_book.id)
        end
    end #end of method

private

    def my_book_params
        params.permit(:edition_id)
    end

    def book_params
      params.permit(:title, :author, :rating)
    end

    def edition_params
        params.permit(:book_id, :title, :author, :edition, :genre, :numberOfPages, :publicationDate, :publisher, :url, :image)
    end

    def find_lend
        @lend = Lend.find_by(my_book_id: params[:id])
    end

end #end of Class

wellRead/app/helpers/books_helper.rb
module BooksHelper
end

wellRead/app/helpers/borrows_helper.rb
module BorrowsHelper
end

wellRead/app/helpers/chats_helper.rb
module ChatsHelper
end

wellRead/app/helpers/editions_helper.rb
module EditionsHelper
end

wellRead/app/helpers/lends_helper.rb
module LendsHelper
end

wellRead/app/helpers/my_books_helper.rb
module MyBooksHelper
end

wellRead/app/helpers/quotes_helper.rb
module QuotesHelper
end

wellRead/app/helpers/ratings_helper.rb
module RatingsHelper
end

wellRead/app/helpers/reviews_helper.rb
module ReviewsHelper
end

wellRead/app/helpers/users_helper.rb
module UsersHelper
end

wellRead/app/views/my_books/index.html.erb
<% @my_books.each do |result|%>
<div class="book_wrapper">
  <div class="book_cover">
    <img src="<%= result.edition.image %>">
  </div>
  <div class="buy">
    <a href="<%= result.edition.url %>"><button class="button_5">Buy Me!</button></a>
  </div>
  <div class="book_details">
    <h1><%= result.edition.title %></h1></br>
    <h2>by <%= result.edition.author %></h2></br>
    <h3><%= result.edition.numberOfPages %> pages</h3></br>
    <h4><%= result.edition.publisher %></h4></br>
  </div>
</div>
<% end %>

wellRead/app/views/my_books/show.html.erb
<div class="prog_statement">
  <h2>Track your reading progress:</h2>
  <input type="text" id="user_page"> of <%= @my_book.edition.numberOfPages %> pages
</div>

<div class="reading_progress">
  <progress id="progressbar" max="<%= @my_book.edition.numberOfPages%>" value="0">
  </progress>
</div>

<div class="book_wrapper">
  <div class="book_cover">
    <img src="<%= @my_book.edition.image %>">
  </div>
  <div class="buy">
    <a href="<%= @my_book.edition.url %>"><button class="button_5">Buy Me!</button></a>
  </div>
  <div class="book_details">
    <h1><%= @my_book.edition.title %></h1></br>
    <h2>by <%= @my_book.edition.author %></h2></br>
    <h3><%= @my_book.edition.numberOfPages %> pages</h3></br>
    <h4><%= @my_book.edition.publisher %></h4></br>
  </div>
  <div class="user_rating">
    <% if @rating == nil %>
      <% @rating = Rating.new%>
      <%= form_for [@book, @rating], url:ratings_url do |f| %>
        <% f.label :rating %>
        <div id="rating-form" >
        <label>Rate this book: </label></br>
        </div>
        <%= f.hidden_field :book_id, value: @my_book.edition.book_id %>
        <span class="rating_submit">
          <button class="button_5"><%= f.submit "Add Rating"%></button>
        </span>
        <%end%>
    <%else%>
       <label>Your rating: </label>
      <span id="rating" data-score="<%= @rating.rating %>">
      </span>
          <%end%>
  </div>
</div>

<div class="review_wrapper">
  <div class="create_review">
    <h1>What did you think?</h1>
    <% @review = Review.new%>
    <%= form_for [@my_book, @review] do |f| %>
      <% f.label :review %>
      <%= f.text_area :review, placeholder: "Best book ever or never-read-again?\n Make your notes here!" %>
      <%= f.hidden_field :my_book_id, value: @my_book.id %>
      <div class="review_submit">
        <%= f.submit "Add Review"%>
      </div>
      <% end %>
  </div>
</div>

<div class="review_content">
  <ul>
    <%@my_book.reviews.each do |review|%>
      <li><%=emojify(review.review) %></li>
      <p class="edit_delete"><%=link_to "Edit", edit_my_book_review_path(review.my_book_id, review.id) %><span class="blue"> | </span>
      <!-- <button class="button_4">Modify this Review</button> -->
      <%=link_to "Delete", my_book_review_path(review.my_book_id, review.id), method: :delete, data: {confirm: "Are you sure?"} %></p>
    <%end%>
  </ul>
</div>

<div class="quote_wrapper_wrapper">
  <p>Store your favourite quotes below!</p>
  <div class="quote_wrapper">
    <a href="<%=my_book_quotes_path(params[:id])%>"><button class="button_4">View Quotes</button></a>
    <a href="<%=new_my_book_quote_path(params[:id]) %>"><button class="button_4">Add a Quote</button></a>
  </div>
</div>

<div class="lend_wrapper">
<% if @lend != nil && @lend.my_book_id == @my_book.id%>
    <%= @my_book.edition.title %> is currently lent out to  <%= @lend.friend %><span class="blue"> | </span>
    <%=link_to "They Returned It", my_book_lend_path(params[:id]), method: :delete, data: {confirm: "Confirm book return"} %>
<%else%>
  <a href="<%=new_my_book_lend_path(params[:id]) %>"><button class="button_4">Lend this book to a friend!</button>
<%end%>
  <!-- <#% if @lend.friend  do%> -->

    <%#=link_to "They Returned It", my_book_lend_path(lend.my_book_id, lend.id), method: :delete, data: {confirm: "Are you sure?"} %>
    <!-- <#% end %> -->
  <%#else%>
    <%#= link_to "Lend this book to a friend", new_my_book_lend_path(lend.my_book_id, lend.id) %>
  <%#end%>
</div>