wellRead/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'users#index'

resources :my_books do
    resources :reviews
    resources :quotes
    resources :lends
end
resources :books do
    resources :conversations do
        resources :chats
    end
end
resources :users do
    resources :borrows
end
resources :libraries
resources :editions
resources :ratings
resources :sessions

get '/search', to: 'books#search'
get '/search', to: 'my_books#search'
post '/booksearch', to: 'books#searchtobook'
post '/my_booksearch', to: 'my_books#searchtomybook'
post '/edition', to: 'edition#create'
post '/chats/new', to: 'chats#create'
post '/borrows/new', to: 'borrows#create'
post 'chats/show', to: 'conversation#show'
# patch '/reviews/update', to: 'reviews#update'
# get '/reviews/edit' to: 'reviews#update'
# post '/reviews/:id/edit', to: 'reviews#update'


end

wellRead/app/models/book.rb
class Book < ApplicationRecord

  has_many :conversations
  has_many :my_books, through: :editions
  has_many :editions
  has_many :ratings
  # belongs to a category

  accepts_nested_attributes_for :conversations

end

wellRead/app/models/borrow.rb
class Borrow < ApplicationRecord
    belongs_to :user
end

wellRead/app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :conversation

end

wellRead/app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :user
  belongs_to :book
  has_many :chats

  accepts_nested_attributes_for :chats

end

wellRead/app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :book

  has_many :my_book

end

wellRead/app/models/lend.rb
class Lend < ApplicationRecord
  belongs_to :my_book
end

wellRead/app/models/library.rb
class Library < ApplicationRecord

  has_many :my_books

  belongs_to :user

end

wellRead/app/models/my_book.rb
class MyBook < ApplicationRecord

  # belongs_to :library
  belongs_to :edition
  has_one :lend
  has_many :reviews
  has_many :quotes
  has_many :books, through: :editions

  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :quotes
  accepts_nested_attributes_for :lend

  # def self.search(search)
  #   MyBook.fuzzy_search(search)
  #   end

end

wellRead/app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :my_book

    mount_uploader :image, QuoteUploader
end

wellRead/app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

wellRead/app/models/review.rb
class Review < ApplicationRecord


  belongs_to :my_book, foreign_key: :my_book_id
 
end

wellRead/app/models/user.rb
class User < ApplicationRecord


  has_secure_password

  has_one :library
  has_many :my_books, through: :library
  has_many :reviews, through: :my_books
  has_many :lends
  has_many :quotes
  has_many :conversations
  has_many :chats
  has_many :borrows
  has_many :ratings

  # accepts_nested_attributes_for :borrows

  # validates :password, length: { minimum: 6 }, on: :create
  # validates :password, confirmation: true, on: :create
  # validates :password_confirmation, presence: true, on: :create
  # validates_uniqueness_of :username, :message => ": This username is already registered!"
  # validates_presence_of :username
  # VALID_EMAIL_REGEX =  /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b
  # validates_presence_of :email, format: {with VALID_EMAIL_REGEX}
  # validates_uniqueness_of :email, :message => ": This email is already registered!"

end

wellRead/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :find_conversation, only: [:show, :edit, :update]
    # before_action :find_chat, only: [:show, :edit, :update, :destroy]
    before_action :find_user


  def index
      @conversations = Conversation.all
  end

  def new
    @conversation = Conversation.new
    @conversations = Conversation.all
    # @edition = Edition.find(params[:book_id])
    @book = Book.find(params[:book_id])
    @chat = Chat.new
  end

  def create
    # @edition = Edition.find(params[:book_id])
    @book = Book.find(params[:book_id])
    @conversation = Conversation.new(conversation_params)
    @conversation.user = current_user

    if @conversation.save!
       @conversation.chats << Chat.new(content: params[:conversation][:chat][:content], user: current_user)


      redirect_to book_conversation_path(@book, @conversation)
    else
      render :new
    end
  end

  def show
    @user.id = current_user.id
    @conversations = Conversation.all

    # need to find a way to say conversation id the chat belongs to
  end

  def edit
  end

  def update
    if @conversation.update(conversation_params)
      # insert flash alert that changes have been saved
          redirect_to book_conversation_path(@conversation)
        else
         render 'edit'
        end
      end

  def destroy
    #   currently Users can't delete conversations as other people may have participated.
    #  however admin would be able to delete a conversation.
  end

private

  def conversation_params
    params.require(:conversation).permit(:book_id, :title, :chats)
  end
  def find_conversation
      @conversation = Conversation.find(params[:id])
  end
  # def find_chat
  #   @chat = Chat.find(params[:chat_id])
  # end
  def find_user
    @user = current_user
  end

end

wellRead/app/helpers/books_helper.rb
module BooksHelper
end

wellRead/app/helpers/borrows_helper.rb
module BorrowsHelper
end

wellRead/app/helpers/chats_helper.rb
module ChatsHelper
end

wellRead/app/helpers/conversations_helper.rb
module ConversationsHelper
end

wellRead/app/helpers/editions_helper.rb
module EditionsHelper
end

wellRead/app/helpers/lends_helper.rb
module LendsHelper
end

wellRead/app/helpers/quotes_helper.rb
module QuotesHelper
end

wellRead/app/helpers/ratings_helper.rb
module RatingsHelper
end

wellRead/app/helpers/reviews_helper.rb
module ReviewsHelper
end

wellRead/app/helpers/users_helper.rb
module UsersHelper
end

wellRead/app/views/conversations/index.html.erb
<h1>Conversation Index</h1>

wellRead/app/views/conversations/new.html.erb
<div class="new_convo_heading">
  <h2>Let's talk about...</h2>
  <h1><%=@book.title %></h1>
</div>

<div class="create_conversation">
  <% @conversation = Conversation.new%>
  <%= form_for [@book, @conversation] do |f| %>
    <p>What do you want to talk about?</p>
    <div class="convo_title">
      <% f.label :title %>
      <%= f.text_field :title, placeholder: "i.e. example..." %>
    </div>

    <p>Oh wow! Go on!</p>
    <div class="chat_body">
      <%= f.fields_for :chat do |chat| %>
        <% chat.label :content %>
        <%= chat.text_area :content, placeholder: "Oh really?" %>
      <% end %>
    </div>
    <%= f.hidden_field :book_id, value: @book.id %>
    <%= f.hidden_field :conversation_id, value: @conversation.id %>
    <%= f.hidden_field :chat_id, value: @chat.id%>
    <div class="new_convo_submit">
      <%= f.submit "Post your conversation!"%>
    </div>
  <% end %>
</div>

wellRead/app/views/conversations/show.html.erb
<h1 class="conversation_title"><%= @conversation.title %></h1>

<div class="create_chat">
  <% @chat = Chat.new%>
  <%= form_for(@chat, :url => book_conversation_chats_path(@conversation.book_id, @conversation.id)) do |f| %>
    <div class="add_chat">
      <% f.label :content %>
      <%= f.text_area :content, placeholder: "Add to the conversation here!" %>
    </div>
    <div class="chat_submit">
      <%= f.submit "Submit"%>
    </div>
  <% end %>
</div>

<div class="chat_thread">
  <% @conversation.chats.each do |chat| %>
  <div class="chat">
    <ul>
        <!-- <li><%#=chat.username%></li> -->
        <li><%=emojify(chat.content)%></li>
        <% a = User.find(chat.user_id)%>
        <p><%= a.username %> <span class="timestamp"><%= time_ago_in_words(chat.created_at) %> ago</span></p>
        <%# if !user_signed_in? %>
            <%if chat.user_id == current_user.id %>
            <p class="edit_delete"><%=link_to "Edit", edit_book_conversation_chat_path(chat.conversation.book_id, chat.conversation_id, chat.id) %><span class="blue"> | </span><%=link_to "Delete", book_conversation_chat_path(chat.conversation_id, chat.id), method: :delete, data: {confirm: "Are you sure?"} %></p>
            <%end%>
        <%#end%>
    </ul>
  </div>
  <%end%>
</div>

 <a href="<%= book_path(params[:book_id]) %>"><button class="button_6">Go back to</br><%= @conversation.book.title %></button></a>