wellRead/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'users#index'

resources :my_books do
    resources :reviews
    resources :quotes
    resources :lends
end
resources :books do
    resources :conversations do
        resources :chats
    end
end
resources :users do
    resources :borrows
end
resources :libraries
resources :editions
resources :ratings
resources :sessions

get '/search', to: 'books#search'
get '/search', to: 'my_books#search'
post '/booksearch', to: 'books#searchtobook'
post '/my_booksearch', to: 'my_books#searchtomybook'
post '/edition', to: 'edition#create'
post '/chats/new', to: 'chats#create'
post '/borrows/new', to: 'borrows#create'
post 'chats/show', to: 'conversation#show'
# patch '/reviews/update', to: 'reviews#update'
# get '/reviews/edit' to: 'reviews#update'
# post '/reviews/:id/edit', to: 'reviews#update'


end

wellRead/app/models/book.rb
class Book < ApplicationRecord

  has_many :conversations
  has_many :my_books, through: :editions
  has_many :editions
  has_many :ratings
  # belongs to a category

  accepts_nested_attributes_for :conversations

end

wellRead/app/models/borrow.rb
class Borrow < ApplicationRecord
    belongs_to :user
end

wellRead/app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :conversation

end

wellRead/app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :user
  belongs_to :book
  has_many :chats

  accepts_nested_attributes_for :chats

end

wellRead/app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :book

  has_many :my_book

end

wellRead/app/models/lend.rb
class Lend < ApplicationRecord
  belongs_to :my_book
end

wellRead/app/models/library.rb
class Library < ApplicationRecord

  has_many :my_books

  belongs_to :user

end

wellRead/app/models/my_book.rb
class MyBook < ApplicationRecord

  # belongs_to :library
  belongs_to :edition
  has_one :lend
  has_many :reviews
  has_many :quotes
  has_many :books, through: :editions

  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :quotes
  accepts_nested_attributes_for :lend

  # def self.search(search)
  #   MyBook.fuzzy_search(search)
  #   end

end

wellRead/app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :my_book

    mount_uploader :image, QuoteUploader
end

wellRead/app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

wellRead/app/models/review.rb
class Review < ApplicationRecord


  belongs_to :my_book, foreign_key: :my_book_id
 
end

wellRead/app/models/user.rb
class User < ApplicationRecord


  has_secure_password

  has_one :library
  has_many :my_books, through: :library
  has_many :reviews, through: :my_books
  has_many :lends
  has_many :quotes
  has_many :conversations
  has_many :chats
  has_many :borrows
  has_many :ratings

  # accepts_nested_attributes_for :borrows

  # validates :password, length: { minimum: 6 }, on: :create
  # validates :password, confirmation: true, on: :create
  # validates :password_confirmation, presence: true, on: :create
  # validates_uniqueness_of :username, :message => ": This username is already registered!"
  # validates_presence_of :username
  # VALID_EMAIL_REGEX =  /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b
  # validates_presence_of :email, format: {with VALID_EMAIL_REGEX}
  # validates_uniqueness_of :email, :message => ": This email is already registered!"

end

wellRead/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :find_my_book
    before_action :find_quote, only: [:edit, :update, :destroy]


    def index
      @quotes = Quote.all
      @my_book = MyBook.find(params[:my_book_id])
    end

    def new
    @quote = Quote.new
    uploader = QuoteUploader.new
    @my_book = MyBook.find(params[:my_book_id])
    end

    def create
      @user = current_user
      @my_book = MyBook.where(user_id: @user.id)
      @quotes = Quote.where(user_id: @user.id)
      @quote = Quote.new(quote_params)
      uploader = QuoteUploader.new

      if @quote.save!
        # redirect_to my_book_url(params[:my_book_id])
        redirect_to my_book_quotes_path(params[:my_book_id])
      else
        render :new
        #above render I think is wrong.
      end
    end

    def edit
    end

    def update
      @quote = Quote.find(params[:id])
      if @quote.update(quote_params)
          # @quote.save!
        # insert flash alert that changes have been saved
        redirect_to my_book_quotes_path
      else
       render 'edit'
      end
    end


    def destroy
        @quote.destroy
        redirect_to my_book_quotes_path(params[:my_book_id])
    end

    def show
      @quote = Quote.find(params[:id])
      @my_book = MyBook.find(params[:my_book_id])
    end

    # def update
    #
    #   if @quote.update_attributes(quote_params)
    #     # insert flash alert that changes have been saved
    #     redirect_to my_book_quotes_path
    #   else
    #     redirect_to :back
    #   end
    # end

    private

    def quote_params
    params.require(:quote).permit( :my_book_id, :quote, :image, :page, :highlight, :id)
    end

    def find_my_book
        @my_book = MyBook.find(params[:my_book_id])
    end
    def find_quote
        @quote = Quote.find(params[:id])
    end
end

wellRead/app/helpers/books_helper.rb
module BooksHelper
end

wellRead/app/helpers/borrows_helper.rb
module BorrowsHelper
end

wellRead/app/helpers/chats_helper.rb
module ChatsHelper
end

wellRead/app/helpers/editions_helper.rb
module EditionsHelper
end

wellRead/app/helpers/lends_helper.rb
module LendsHelper
end

wellRead/app/helpers/my_books_helper.rb
module MyBooksHelper
end

wellRead/app/helpers/quotes_helper.rb
module QuotesHelper
end

wellRead/app/helpers/ratings_helper.rb
module RatingsHelper
end

wellRead/app/helpers/reviews_helper.rb
module ReviewsHelper
end

wellRead/app/helpers/users_helper.rb
module UsersHelper
end

wellRead/app/views/quotes/edit.html.erb
<div class="modify_quote_form">
  <div class="show_quote_content">
    <%= @quote.quote %>
  </div>
    <%= form_for [@my_book, @quote] do |f| %>
      <div class="modify_quote_wrapper">
        <p>Update your quote below</p>
        <% f.label "Quote" %>
        <%= f.text_area :quote %>
      </div>
      <div class="modify_quote_form_submit">
        <%= f.submit "Update Quote" %>
      </div>
    <% end %>
</div>

wellRead/app/views/quotes/index.html.erb
<div class="index_quote_wrapper">
  <div class="book_quote_title">
    <h1><%=@my_book.edition.title%></h1>
  </div>
  <h2>by <%=@my_book.edition.author%></h2>

  <% quotes = @my_book.quotes.count %>
  <% if quotes == 0 %>
  <p>It doesn't look like you've added any quotes yet...</p>
  <% else %>
  <ul>
    <% @my_book.quotes.each do |quote| %>
      <% i = quote.id %>
      <li><b>Page <%= quote.page %>:</b>
      <div class="index_quote_show">
        <%=quote.quote%>
        <div id="index_quote_image" style="background-image:url(<%= quote.image %>)">
          <div id="show_highlight" style="background-image: url(<%=quote.highlight%>)"></div>
        </div>
      </div>
      <div class="edit_delete">
      <% if quote.quote != nil %>
        <%=link_to "Edit", edit_my_book_quote_path(quote.my_book_id, quote.id) %>
      <% else %>
        <%= link_to "Highlight Quote", my_book_quote_path(params[:my_book_id], i) %>
      <% end %><span class="blue"> | </span>
      <%=link_to "Delete", my_book_quote_path(quote.my_book_id, quote.id), method: :delete, data: {confirm: "Are you sure you want to delete this quote?"} %>
      </div>
      </li>
    <% end %>
  </ul>
  <% end %>
  <a href="<%=new_my_book_quote_path(params[:my_book_id]) %>"><button class="button_4">Add a Quote</button></a>
</div>

wellRead/app/views/quotes/new.html.erb
<div class="new_quote_wrapper">
  <div class="create_quote">
    <div class="quote_header">
      <h3>Add a quote from</h3> <h1><%=@my_book.edition.title%></h1>
    </div>
    <% @quote = Quote.new%>
    <%= form_for [@my_book, @quote] do |f| %>
      <%= f.hidden_field :my_book_id, value: @my_book.id %>
      <% f.label :quote %>
      <%= f.text_area :quote, placeholder: "Add your favourite line here!" %>
      <% f.label :page %>
      <div class="quote_submit">
        <%= f.number_field :page, placeholder: "What page was that on?" %>
        <%= f.submit "Create Quote"%>
      </div>
    <% end %>
  </div>
  <div class="quote_image_upload">
    <p>Don't want to type that quote out? That's okay! Take a picture of it instead!</p>
    <%= form_for [@my_book, @quote], html: { multipart: true } do |f| %>
      <!-- <%# if @quote.errors.any? %>
        <div id="error_explanation">
          <h2><%#= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

          <ul>
          <%# @quote.errors.full_messages.each do |message| %>
            <li><%#= message %></li>
          <%# end %>
          </ul>
        </div>
      <%# end %> -->
        <% f.label :image %>
        <%= f.file_field :image %>
        <% f.label :page %>
        <%= f.number_field :page, placeholder: "What page was that on?"  %>
        <%= f.hidden_field :my_book_id, value: @my_book.id %>
        <%= f.submit %>
    <% end %>
  </div>
</div>

wellRead/app/views/quotes/show.html.erb
<h1 class="highlight_title">Highlight your quote below!</h1>

<div class="quote_show" style="overflow:hidden;">
  <div id="quote_image" style="background-image: url(<%= @quote.image %>);">
    <canvas id="highlight">
    </canvas>
  </div>
</div>
<%= form_for [@my_book, @quote], :html => {:id => "highlight_form"} do |f| %>
  <%= f.hidden_field :id, value: @quote.id %>
  <%= f.hidden_field :my_book_id, value: @my_book.id %>
  <%= f.hidden_field :highlight, value: "" %>
  <div class="save_highlight">
    <%= f.submit "Save!" %>
  </div>
<% end %>