wellRead/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'users#index'

resources :my_books do
    resources :reviews
    resources :quotes
    resources :lends
end
resources :books do
    resources :conversations do
        resources :chats
    end
end
resources :users do
    resources :borrows
end
resources :libraries
resources :editions
resources :ratings
resources :sessions

get '/search', to: 'books#search'
get '/search', to: 'my_books#search'
post '/booksearch', to: 'books#searchtobook'
post '/my_booksearch', to: 'my_books#searchtomybook'
post '/edition', to: 'edition#create'
post '/chats/new', to: 'chats#create'
post '/borrows/new', to: 'borrows#create'
post 'chats/show', to: 'conversation#show'
# patch '/reviews/update', to: 'reviews#update'
# get '/reviews/edit' to: 'reviews#update'
# post '/reviews/:id/edit', to: 'reviews#update'


end

wellRead/app/models/book.rb
class Book < ApplicationRecord

  has_many :conversations
  has_many :my_books, through: :editions
  has_many :editions
  has_many :ratings
  # belongs to a category

  accepts_nested_attributes_for :conversations

end

wellRead/app/models/borrow.rb
class Borrow < ApplicationRecord
    belongs_to :user
end

wellRead/app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :conversation

end

wellRead/app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :user
  belongs_to :book
  has_many :chats

  accepts_nested_attributes_for :chats

end

wellRead/app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :book

  has_many :my_book

end

wellRead/app/models/lend.rb
class Lend < ApplicationRecord
  belongs_to :my_book
end

wellRead/app/models/library.rb
class Library < ApplicationRecord

  has_many :my_books

  belongs_to :user

end

wellRead/app/models/my_book.rb
class MyBook < ApplicationRecord

  # belongs_to :library
  belongs_to :edition
  has_one :lend
  has_many :reviews
  has_many :quotes
  has_many :books, through: :editions

  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :quotes
  accepts_nested_attributes_for :lend

  # def self.search(search)
  #   MyBook.fuzzy_search(search)
  #   end

end

wellRead/app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :my_book

    mount_uploader :image, QuoteUploader
end

wellRead/app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

wellRead/app/models/review.rb
class Review < ApplicationRecord


  belongs_to :my_book, foreign_key: :my_book_id
 
end

wellRead/app/models/user.rb
class User < ApplicationRecord


  has_secure_password

  has_one :library
  has_many :my_books, through: :library
  has_many :reviews, through: :my_books
  has_many :lends
  has_many :quotes
  has_many :conversations
  has_many :chats
  has_many :borrows
  has_many :ratings

  # accepts_nested_attributes_for :borrows

  # validates :password, length: { minimum: 6 }, on: :create
  # validates :password, confirmation: true, on: :create
  # validates :password_confirmation, presence: true, on: :create
  # validates_uniqueness_of :username, :message => ": This username is already registered!"
  # validates_presence_of :username
  # VALID_EMAIL_REGEX =  /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b
  # validates_presence_of :email, format: {with VALID_EMAIL_REGEX}
  # validates_uniqueness_of :email, :message => ": This email is already registered!"

end

wellRead/app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
    def show
        @user = current_user
        @my_books = MyBook.where(user_id: @user.id)
        # raise "hi meg"

    end
end

wellRead/app/helpers/books_helper.rb
module BooksHelper
end

wellRead/app/helpers/borrows_helper.rb
module BorrowsHelper
end

wellRead/app/helpers/chats_helper.rb
module ChatsHelper
end

wellRead/app/helpers/editions_helper.rb
module EditionsHelper
end

wellRead/app/helpers/lends_helper.rb
module LendsHelper
end

wellRead/app/helpers/libraries_helper.rb
module LibrariesHelper
end

wellRead/app/helpers/quotes_helper.rb
module QuotesHelper
end

wellRead/app/helpers/ratings_helper.rb
module RatingsHelper
end

wellRead/app/helpers/reviews_helper.rb
module ReviewsHelper
end

wellRead/app/helpers/users_helper.rb
module UsersHelper
end

wellRead/app/views/libraries/index.html.erb
<h1>Welcome to your Library </h1>

wellRead/app/views/libraries/show.html.erb
<div class="book_pile">

  <div class="bookshelf">
    <div class="front"></div>
    <div class="side"></div>
    <div class="top"></div>
    <div class="middle"></div>
    <div class="topside"></div>
  </div>

  <%@my_books.each do |book| %>
  <%book_pile_look=["book_style1", "book_style2", "book_style3", "book_style4", "book_style5"]%>
     <div class="<%=book_pile_look.sample %>">
       <div class="book_top"></div>
       <div class="book_top_width"></div>
       <div class="book_cover">
         <div class="inner_border">
           <div class="stripe1"></div>
           <div class="stripe2"></div>
           <div class="spine">
             <% edition = Edition.find(book.edition_id) %>
             <%=link_to edition.title, my_book_path(book) %>
           </div>
           <div class="stripe3"></div>
           <div class="stripe4"></div>
           <div class="stripe5"></div>
         </div>
       </div>
       <div class="book_bottom_width"></div>
       <div class="book_pages"></div>
     </div>
  <%end%>
</div>

<nav class="library_nav">
  <a href="<%= user_path %>"><button class="button_2">My Profile</button></a>
  <a href="<%= books_path %>"><button class="button_2">Booksearch</button></a>
  <a href="<%= my_books_path %>"><button class="button_2">Booklist</button></a>
  <a href="<%= new_user_borrow_path(@user.id) %>"><button class="button_2">Borrow</button></a>
</nav>